### ISSUE TITLE
Error setting a different URL

### ISSUE THREAD

**Issue by christ0pher** [dockware/dockware#40] opened 2021-02-02 15:22 UTC
Hi! Thanks for this epic project. It helps tremendously in day to day development.

**Describe the bug**
We encounter a weird error when setting a custom URL. 
We adjusted the entrypoint.sh for our purpose and added:
`sudo echo "127.0.0.1 $2" >> /etc/hosts`
`sudo mysql --user=root --password=root -e "use shopware; update sales_channel_domain set url='$1' where url='http://localhost';"`
After that we clear the cache with:
`rm -rf /var/www/html/var/cache/*`
`/var/www/html/bin/console cache:clear`

We also have our own .env where the APP_URL is replaced with the AWS URL.

Before we apply those changes a cURL call to localhost returns a 200. After that we get a 500 and we can not start the container.
We want to use this within Lightsail from AWS to create test instances for our shopware app. 

**To Reproduce**
We create our own image using a custom entrypoint (which is copied from the current play version) and we added:
`sudo echo "127.0.0.1 $2" >> /etc/hosts`
`export APP_URL=$1`
`sudo mysql --user=root --password=root -e "use shopware; select * from sales_channel_domain"`
`sudo mysql --user=root --password=root -e "use shopware; update sales_channel_domain set url='$1' where url='http://localhost';"`
`sudo mysql --user=root --password=root -e "use shopware; select * from sales_channel_domain"`
`rm -rf /var/www/html/var/cache/*`
`/var/www/html/bin/console cache:clear`
`/var/www/html/bin/console dal:refresh:index`

In this case $1 and $2 are the corresponding URL and Domain from AWS Lightsail Container Service.

**Expected behavior**
Corresponding to the documentation and custom domains we should only update the sales_channel_domain table and the /etc/hosts. (https://dockware.io/docs#custom-domains)

**Additional context**
We use the container service from AWS Lightsail and create our custom image which is pushed to lightsail.

**Comment by boxblinkracer** [comment] 2021-02-17 13:05
hi

thanks for your kind words

it should actually indeed work really simple.
so first thing is, that the shop needs to listen for that domain,
so double check the sales channel domain (including http(s) protocol).

then all you actually need to do, is to make sure the shop is available. if you are developing locally, then it requires a etc/host entry. if you are on a real server, like AWS, then you only need to makre sure the domain DNS points to your server, and that port 80 and 443 is epxosed and routing to your docker container...

in between....cache clearing :)

doing a /etc/host on a live server, is only necessary if you want to redirect the local url calls on the internal network instead through the domain and dns (public routing)

lets start with this
run it locally, update the sales channel domain, clear caches...and then add your /etc/host entry for your local setup.
if it then works, then the problem is not in the DB domain change (if its also like this on AWS) but then the routing to the server might have some troubles

**Comment by christ0pher** [comment] 2021-03-04 13:14
Hey thanks for the response!

Our goal was do pre-built the Docker image with a specific URL already included. 

If I understand you correctly: The URL I want to assign needs to point to the correct IP -BEFORE- I change the settings in the DB and clear the caches?

**Comment by boxblinkracer** [comment] 2021-03-19 11:01
Hi Christopher

sorry for the late reply
i did a documentation page for you
https://docs.dockware.io/development/custom-domains

so your outer environment needs to have that custom domain point to a proxy or the shop container...
and then the shop container has to have 2 things
        a) the correct domain and http protocol in the sales channel
        b) ...a cleared cache

the timing doesnt really make a difference, it only just starts working after everything is changed and caches are cleared

then it should work

**Comment by boxblinkracer** [comment] 2021-03-30 20:56
Hi
just wanted to reach out, if you need any additional help?

**Comment by christ0pher** [comment] 2021-05-03 15:17
Hey,

no thanks it is working as intended. The main idea was to directly bake those domain changes into a docker image. But following you description I created a script which can be executed on startup (from the docker host) and adjust the domains.

`
#!/usr/bin/env bash

SW_NAME=$1
URL=$2
IMAGE_TAG=$3

sudo docker run --name shopware6_${SW_NAME} -e APP_URL=${URL} -d -p 80:80 dockware/play:${IMAGE_TAG}
docker exec -it shopware6_${SW_NAME} sudo mysql --user=root --password=root -e "use shopware; update sales_channel_domain set url='${URL}' where url='http://localhost';"
docker exec -it shopware6_${SW_NAME} bin/console app:url-change:resolve;
docker exec -it shopware6_${SW_NAME} bin/console cache:clear;
curl -s -o /dev/null -v  ${URL}
`

**Comment by boxblinkracer** [comment] 2021-06-04 20:46
perfect
thanks for letting me know
that sounds indeed legit

theres now a tutorial on creating custom images based on dockware. maybe it helps
https://docs.dockware.io/development/custom-images

i will now close this ticket. feel free to reach out again

**Closed by boxblinkracer** 2021-06-04 20:46 UTC
Labels: help wanted

**Comment by casdep** [comment] 2022-03-10 19:40
@christ0pher I am trying to do exactly this, start dockware and switch the "localhost" domain to something else. "dockware-local" for example, I am trying to do so using the boot_end.sh file as described [in this doc.](https://docs.dockware.io/development/custom-images)

I can not seem to find the docker-compose file where I can reference this script for when dockware boots. Can you explain me how you made your script run (or where you found the docker-compose.yml file possibly)?

Kind regards

**Comment by martinweinmayr** [comment] 2022-03-11 06:48
@casdep you have to create the docker-compose.yml by your self per project.
You can find great exmaples in our dockware/exmplaes repository.

**Comment by casdep** [comment] 2022-03-11 09:17
@martinweinmayr Thank you!

I am quite new to Docker and containers, I currently generated a `docker-compose.yml` file and a `boot_end.sh` file. I trying to use the boot file to generate a admin root user and change the localhost URL to "_dockware-local.com_".

Could you explain me how I can execute the `docker-compose.yml` file? I currently boot dockware using:
`docker run --rm -p 80:80 dockware/play:latest`

Neither can I seem to find the `docker-compose.yml` file in my windows explorer, but this could be because it is in a docker image?

**Comment by casdep** [comment] 2022-03-11 09:27
@martinweinmayr The thing is that I generated all these files via the CLI using Docker Desktop.  I can not locate this `docker-compose.yml` file in my windows explorer. Neither can I boot it using the Docker Desktop CLI after I executed `docker run`:
![image](https://user-images.githubusercontent.com/22540169/157839746-272338d6-da3d-4770-b328-f76c4570c435.png)

**Comment by martinweinmayr** [comment] 2022-03-11 09:30
docker-compose !== docker-desktop.
you need to install it additionally

**Comment by casdep** [comment] 2022-03-11 09:59
@martinweinmayr I hope I dont bother you, but I do have docker-compose installed.

U just dont understand how I can run dockware using `docker-compose`. I delibrately use dockware as recommended in [this German post](https://forum.shopware.com/t/shopware-6-lokal-auf-windows-installieren/91883/2). 

As described [here](https://docs.dockware.io/use-dockware/first-run), I can run Dockware using the `docker run` command wich can be executed regardless of the folder or directory where CMD instance is. But `docker-compose` **must** be executed in the same directory as that file is.

So my question still is, how can I run` docker-compose` since I can not find this file in my Windows explorer. Only in my docker image CLI which I start using docker, seen in the image below.
![image](https://user-images.githubusercontent.com/22540169/157845052-c18b3779-e78b-426a-aab4-1b0216b4f232.png)

**Comment by martinweinmayr** [comment] 2022-03-11 10:09
@casdep as i tryed to explain in the first repsonse, you have to create the docker-compose.yml by your self for evrey setup.
The same as you habe to with composer files.

so pls try this:


1. stop your running containers
2. copy the file from https://github.com/dockware/examples/blob/master/basic-dev-setup/docker-compose.yml
3. locate it in your explorer in C:\my-setup or some other place
4. open your cli and go to C:\my-setup 
5. type `docker-compose up -d`

**Comment by casdep** [comment] 2022-03-11 10:17
@martinweinmayr  I see... I created the docker-compose.yml *inside* my docker container, hence I could never see nor execute it...

Thanks for your time and effort sir!!
